# Generated by Django 4.0.4 on 2022-05-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_todolist_end_hour_alter_todolist_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
