# Generated by Django 4.0.4 on 2022-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_todolist_is_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
